name: "CI: Unit Tests"

on: [push]

jobs:
  check-unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      - name: Install packages
        run: yarn install --prefer-offline

      - name: Run Unit Tests
        run: yarn test:unit

      - name: Run Integration Tests
        run: yarn test:integration

      - name: Run Test Coverage
        run: yarn test:cov

      - name: Coveralls Report
        uses: coverallsapp/github-action@v1.1.2
        with:
          path-to-lcov: './tests/coverage/lcov.info'
          github-token: ${{ secrets.GITHUB_TOKEN }}
